# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIv2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MainPage(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(605, 619)
        self.cancel_button = QtWidgets.QPushButton(Form)
        self.cancel_button.setGeometry(QtCore.QRect(400, 540, 171, 61))
        self.cancel_button.setObjectName("cancel_button")
        self.pay_button = QtWidgets.QPushButton(Form)
        self.pay_button.setGeometry(QtCore.QRect(400, 470, 171, 61))
        self.pay_button.setObjectName("pay_button")
        self.table = QtWidgets.QTableWidget(Form)
        self.table.setGeometry(QtCore.QRect(50, 100, 511, 281))
        self.table.setObjectName("table")
        self.table.setColumnCount(4)
        #self.table.setRowCount(4)
        self.table.setHorizontalHeaderLabels(['Name','number','price','number*price'])
        self.time = QtWidgets.QLabel(Form)
        self.time.setGeometry(QtCore.QRect(50, 20, 175, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(18)
        self.time.setFont(font)
        self.time.setObjectName("time")
        self.welcome = QtWidgets.QLabel(Form)
        self.welcome.setGeometry(QtCore.QRect(50, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.welcome.setFont(font)
        self.welcome.setObjectName("welcome")
        self.login_button = QtWidgets.QPushButton(Form)
        self.login_button.setGeometry(QtCore.QRect(410, 30, 141, 51))
        self.login_button.setObjectName("login_button")
        self.price = QtWidgets.QLabel(Form)
        self.price.setGeometry(QtCore.QRect(200, 400, 400, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.price.setFont(font)
        self.price.setObjectName("price")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cancel_button.setText(_translate("Form", "CANCEL"))
        self.pay_button.setText(_translate("Form", "PAY"))
        self.time.setText(_translate("Form", "date_tome"))
        self.welcome.setText(_translate("Form", "welcome"))
        self.login_button.setText(_translate("Form", "login"))
        self.price.setText(_translate("Form", "total price"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = MainPage()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
